import { createRequestHandler } from "@remix-run/cloudflare";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "./build/server";

const requestHandler = createRequestHandler(build);

export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext
  ): Promise<Response> {
    return requestHandler(request, {
      cloudflare: {
        env,
        ctx,
        cf: request.cf!,
        caches,
      },
    });
  },
};
