# After editing this file run npm run typegen to regenerate the types
name = "bithellstudios-telemetry-and-analytics"
pages_build_output_dir = "public"
compatibility_date = "2023-12-31"
send_metrics = true 


# Applies to both the local and the preview environments (but not the production environment) - ie PR previews etc. Normally when developing locally though you are using a local db
[[d1_databases]]
database_id = "572b82f0-c3c2-4f55-aa10-39d902a3959f"
binding = "DB"
database_name = "DB"
migrations_table = "migrations" # Customize this value to change your applied migrations table name
migrations_dir = "migrations"

# Apply only to the production environment
[[env.production.d1_databases]]
database_id = "67e79b07-81ca-4e5c-ab60-323e45555e11"
binding = "DB"
database_name = "DB"
migrations_table = "migrations" # Customize this value to change your applied migrations table name
migrations_dir = "migrations"