# After editing this file run npm run typegen to regenerate the types
name = "bithellstudios-telemetry-and-analytics"
pages_build_output_dir = "public"
compatibility_date = "2023-12-31"
send_metrics = true 


# Applies to both the local and the preview environments (but not the production environment) - ie PR previews etc. Normally when developing locally though you are using a local db
[[d1_databases]]
database_id = "1bddda40-e899-4ab5-a901-e4c92404a361"
binding = "DB"
database_name = "DB"

# Apply only to the production environment
[[env.production.d1_databases]]
database_id = "1bddda40-e899-4ab5-a901-e4c92404a361"
binding = "DB"
database_name = "DB"
