on:
  workflow_dispatch:
name: Reset the preview database to base state
run-name: Reset the preview database triggered by @${{ github.actor }}
jobs:
  reset:
    runs-on: ubuntu-latest
    name: Reset database
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Drop tables
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "3.51.0"
          packageManager: npm
          command: d1 execute DB --preview --remote=true --command="PRAGMA defer_foreign_keys = true; DROP TABLE IF EXISTS migrations adamrmsinstallations; PRAGMA defer_foreign_keys = false;"
      - name: Run migrations from main branch
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "3.51.0"
          packageManager: npm
          command: d1 migrations apply DB --preview --remote=true"
